// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FarAwayClient.Models;

public partial class AdditionalServicesForRent
{
    public int IdRent { get; set; }

    public int IdService { get; set; }

    public int FrequencyOfServicePerformanceInDays { get; set; }

    public int IdServiceProviders { get; set; }

    public virtual FrequencyOfService FrequencyOfServicePerformanceInDaysNavigation { get; set; }

    public virtual ParkingSpaceRental IdRentNavigation { get; set; }

    public virtual ListOfAdditionalService IdServiceNavigation { get; set; }

    public virtual ServiceProvider IdServiceProvidersNavigation { get; set; }
}