// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FarAwayClient.Models;

public partial class Branch
{
    public int Id { get; set; }

    public int IdTypeOfParking { get; set; }

    public int? IdTypeOfCarExchangeSystem { get; set; }

    public string Address { get; set; }

    public virtual BranchCharacteristic BranchCharacteristic { get; set; }

    public virtual TypesOfCarExchangeSystem IdTypeOfCarExchangeSystemNavigation { get; set; }

    public virtual TypesOfParking IdTypeOfParkingNavigation { get; set; }

    public virtual ICollection<ParkingSpot> ParkingSpots { get; set; } = new List<ParkingSpot>();
}