// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FarAwayClient.Models;

public partial class BranchCharacteristic
{
    public int Id { get; set; }

    public int CountOfParkingSpaces { get; set; }

    public decimal TheCostOfAparkingSpacePerDay { get; set; }

    public int WidthOfTheLiftingAndLoweringMechanismInMillimeters { get; set; }

    public int TotalWidthOfTheCarInMillimeters { get; set; }

    public int MaximumCarLengthInMillimeters { get; set; }

    public int MaximumHeightOfTheVehicleInMillimeters { get; set; }

    public int MaximumVehicleWeightInKilograms { get; set; }

    public virtual Branch IdNavigation { get; set; }
}