// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FarAwayClient.Models;

public partial class FrequencyOfService
{
    public int Id { get; set; }

    public string FrequencyName { get; set; }

    public virtual ICollection<AdditionalServicesForRent> AdditionalServicesForRents { get; set; } = new List<AdditionalServicesForRent>();
}