// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FarAwayClient.Models;

public partial class ParkingSpot
{
    public int Id { get; set; }

    public int IdBranch { get; set; }

    public int IdParkingSpotStatus { get; set; }

    public virtual Branch IdBranchNavigation { get; set; }

    public virtual ParkingSpotStatus IdParkingSpotStatusNavigation { get; set; }

    public virtual ICollection<ParkingSpaceRental> ParkingSpaceRentals { get; set; } = new List<ParkingSpaceRental>();
}