// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FarAwayClient.Models;

public partial class ParkingSpaceRental
{
    public int Id { get; set; }

    public int IdTypeOfRentByDuration { get; set; }

    public int IdUser { get; set; }

    public int IdParkingSpot { get; set; }

    public DateTime RentalStartDate { get; set; }

    public DateTime? RentEndDate { get; set; }

    public decimal? TotalPrice { get; set; }

    public int IdRentalStatus { get; set; }

    public virtual ICollection<AdditionalServicesForRent> AdditionalServicesForRents { get; set; } = new List<AdditionalServicesForRent>();

    public virtual ParkingSpot IdParkingSpotNavigation { get; set; }

    public virtual RentalStatus IdRentalStatusNavigation { get; set; }

    public virtual TypeOfRentByDuration IdTypeOfRentByDurationNavigation { get; set; }

    public virtual User IdUserNavigation { get; set; }
}