// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FarAwayClient.Models;

public partial class TypeOfRentByDuration
{
    public int Id { get; set; }

    public string TypeName { get; set; }

    public int MinDurationOfRentalDays { get; set; }

    public int? MaxDurationOfRentalDays { get; set; }

    public decimal PriceCoefficient { get; set; }

    public virtual ICollection<ParkingSpaceRental> ParkingSpaceRentals { get; set; } = new List<ParkingSpaceRental>();
}