// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FarAwayClient.Models;

public partial class TypesOfParking
{
    public int Id { get; set; }

    public string TypeName { get; set; }

    public virtual ICollection<Branch> Branches { get; set; } = new List<Branch>();
}