// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FarAwayClient.Models;

public partial class User
{
    public int Id { get; set; }

    public string Surname { get; set; }

    public string Name { get; set; }

    public string Patronymic { get; set; }

    public string Email { get; set; }

    public string Login { get; set; }

    public string Password { get; set; }

    public string PhoneNumber { get; set; }

    public byte[] Photo { get; set; }

    public int IdRole { get; set; }

    public virtual Role IdRoleNavigation { get; set; }

    public virtual ICollection<ParkingSpaceRental> ParkingSpaceRentals { get; set; } = new List<ParkingSpaceRental>();
}